repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: name-tests-test
      - id: check-yaml
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
    -   id: pyupgrade
  - repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black